added rate limits to each room by author group and author
utmgdsc/hacklab-booking pull request #245
Opened 2024-11-06 05:00 UTC by FrederickPu

added rate limits on the number of pending requests for on a room for each user and group

Note: still have not created a constant for the maximum number of pending requests (it's a hardcoded value).

2024-11-06 05:05 UTC, FrederickPu commented
#148

2024-11-06 15:16 UTC, ggggg commented
Ideally, we would make it into a per-room setting in the future. Unfortunately, room settings arent really a thing right now...

2024-11-06 15:18 UTC, ggggg commented
The original issue does state that limits should be "per room." If you could make that change, it'd be great!

2024-11-06 15:27 UTC, FrederickPu commented
> The original issue does state that limits should be "per room." If you could make that change, it'd be great!
Isn't it already doing that since the db request already only finds pending requests with the current room name?

2024-11-06 16:51 UTC, ggggg commented
Sorry, I meant configured per room, as in, making an adjustable setting for each room

2024-11-06 16:56 UTC, FrederickPu commented
so you mean change the db so that the admin can configure pr room limits?

2024-11-06 17:18 UTC, ggggg requested changes

2024-11-06 17:18 UTC, ggggg commented on backend/src/models/requestsModel.ts
> +    })
This info can be fetched when fetching this user, try limiting the number of DB queries

2024-11-06 17:18 UTC, ggggg commented on backend/src/models/requestsModel.ts
> +    })
Same as the other comment

2024-11-06 17:25 UTC, ggggg commented on backend/src/models/requestsModel.ts
> +    if (pendingUser.length > (room?.capacity || 10)) {
```suggestion
    if (pendingUser.length > (room?.requestLimit || 10)) {
```

2024-11-06 17:25 UTC, ggggg commented on backend/src/models/requestsModel.ts
> +    if (pendingGroup.length > (room?.capacity || 10)) {
```suggestion
    if (pendingGroup.length > (room?.requestLimit || 10)) {
```

2024-11-06 21:36 UTC, logonoff commented on backend/src/models/requestsModel.ts
> +        status: 403,
should this be http 429

2024-11-06 21:36 UTC, logonoff commented on backend/src/models/requestsModel.ts
> +        status: 403,
should this be http 429: too many requests

2024-11-07 03:04 UTC, ggggg commented on backend/src/models/requestsModel.ts
> +
```suggestion
    if (userFetched.requests.length >= room.requestLimit || userFetched.groups[0].requests.length >= room.requestLimit) {
      return {
        status: 429,
        message: 'User has too many pending requests.',
      }
    }
   
```

2024-11-07 03:04 UTC, ggggg approved these changes

2024-11-07 03:08 UTC, merged